language: python
python:
 - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./build.sh
  - make cover
  #- python ./homework2/tests/test_RBTree.py
  #- coverage run -m unittest discover -v
#  - pytest # or py.test for Python versions 3.5 and below
